# Generated by Django 4.2.1 on 2023-06-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crud_delete_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crud',
            new_name='Periodista',
        ),
    ]
