# Generated by Django 4.2.1 on 2023-06-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_crud_periodista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodista',
            old_name='Rango',
            new_name='rango',
        ),
    ]
